spring:

  # spring datasource
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/db_loader?autoReconnect=true
    username: root
    password:
    poolName: SpringBootHikariCP
    maximumPoolSize: 5
    minimumIdle: 3
    maxLifetime: 2000000
    connectionTimeout: 30000
    idleTimeout: 30000

  # spring hibernate
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# konfigurasi log
logging:
  level:
    org:
      hibernate: DEBUG