spring:

  # spring datasource
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3307/db_loader
    username: root
    password: root
    poolName: SpringBootHikariCP
    maximumPoolSize: 5
    minimumIdle: 3
    maxLifetime: 2000000
    connectionTimeout: 30000
    idleTimeout: 30000

  # spring hibernate
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  batch:
    initialize-schema: always

# konfigurasi log
logging:
  level:
    org:
      hibernate: DEBUG
